
export const data =
    [
        {
            "id": "1",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Tiger Nixon",
        },
        {
            "id": "2",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Garrett Winters",
        },
        {
            "id": "3",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Ashton Cox",
        },
        {
            "id": "4",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Cedric Kelly",
        },
        {
            "id": "5",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Airi Satou",
        },
        {
            "id": "6",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Brielle Williamson",
        },
        {
            "id": "7",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Herrod Chandler",
        },
        {
            "id": "8",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Rhona Davidson",
        },
        {
            "id": "9",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Colleen Hurst",
        },
        {
            "id": "10",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Sonya Frost",
        },
        {
            "id": "11",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Jena Gaines",
        },
        {
            "id": "12",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Quinn Flynn",
        },
        {
            "id": "13",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Charde Marshall",
        },
        {
            "id": "14",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Haley Kennedy",
        },
        {
            "id": "15",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Tatyana Fitzpatrick",
        },
        {
            "id": "16",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Michael Silva",
        },
        {
            "id": "17",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Paul Byrd",
        },
        {
            "id": "18",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Gloria Little",
        },
        {
            "id": "19",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Bradley Greer",
        },
        {
            "id": "20",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Dai Rios",
        },
        {
            "id": "21",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Jenette Caldwell",
        },
        {
            "id": "22",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Yuri Berry",
        },
        {
            "id": "23",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Caesar Vance",
        },
        {
            "id": "24",
            "employee_lastName": "walker",
            "employee_email": "walker@gmail.com",
            "employee_phone": "9999596751",
            "employee_address": "delhi",
            "employee_name": "Doris Wilder",
        },
    ]
